### PR TITLE
Added support for using overrides in the project bower.json

### PR DESCRIPTION
**Pull request by geo242**

### CODE REVIEW

**Comment by benmarch** [comment]
Hi @geo242,

Thank you for this PR, it is a feature I have been meaning to add for a while now. I just have one question: is there a reason you went with the overrides in the manifest file instead of the Grunt configuration? I don't think that overrides is a standard block in the manifest (please correct me if I am wrong) and I am not aware of other tasks that use it that way. I was thinking that overrides could be a task or target option for more flexibility. What do you think?

Thanks,
Ben

**Comment by geo242** [comment]
The reason I implemented it to look at the project bower.json is because wiredep already supports this way of doing it, so if you use wiredep and this plugin, they will work together seamlessly. 

Adding an additional way of configuring through the grunt configuration seems like a good idea too, and I can work on that next if you like.

**Comment by benmarch** [comment]
Ah ok cool, looks good to me. If you wouldn't mind adding the option to use the Gruntfile config that would be awesome to have also. Thanks!

**Comment by benmarch** [comment]
Hey @geo242, I had some time so I added overrides to grunt config. Released version 0.2.0 with both changes.

**Comment by geo242** [comment]
@benmarch sweet! thanks!

**Pull request merged**
